[package]
name = "make_move"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.15.1", default-features = false, features = ["std"] }
game = { path = "../../game" }
